=begin
#NetSchool

#The API for the NetSchool irTech project

OpenAPI spec version: 5.10.63221

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LoginAccountInfoOrganizations
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LoginAccountInfoOrganizations' do
  before do
    # run before each test
    @instance = SwaggerClient::LoginAccountInfoOrganizations.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoginAccountInfoOrganizations' do
    it 'should create an instance of LoginAccountInfoOrganizations' do
      expect(@instance).to be_instance_of(SwaggerClient::LoginAccountInfoOrganizations)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
