/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssignmentTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssignmentTypesTests
    {
        // TODO uncomment below to declare an instance variable for AssignmentTypes
        //private AssignmentTypes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssignmentTypes
            //instance = new AssignmentTypes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssignmentTypes
        /// </summary>
        [Test]
        public void AssignmentTypesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssignmentTypes
            //Assert.IsInstanceOfType<AssignmentTypes> (instance, "variable 'instance' is a AssignmentTypes");
        }



    }

}
