/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Diary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DiaryTests
    {
        // TODO uncomment below to declare an instance variable for Diary
        //private Diary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Diary
            //instance = new Diary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Diary
        /// </summary>
        [Test]
        public void DiaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Diary
            //Assert.IsInstanceOfType<Diary> (instance, "variable 'instance' is a Diary");
        }


        /// <summary>
        /// Test the property 'WeekStart'
        /// </summary>
        [Test]
        public void WeekStartTest()
        {
            // TODO unit test for the property 'WeekStart'
        }
        /// <summary>
        /// Test the property 'WeekEnd'
        /// </summary>
        [Test]
        public void WeekEndTest()
        {
            // TODO unit test for the property 'WeekEnd'
        }
        /// <summary>
        /// Test the property 'WeekDays'
        /// </summary>
        [Test]
        public void WeekDaysTest()
        {
            // TODO unit test for the property 'WeekDays'
        }
        /// <summary>
        /// Test the property 'TermName'
        /// </summary>
        [Test]
        public void TermNameTest()
        {
            // TODO unit test for the property 'TermName'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Test]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }

    }

}
