/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginFormTests
    {
        // TODO uncomment below to declare an instance variable for LoginForm
        //private LoginForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginForm
            //instance = new LoginForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginForm
        /// </summary>
        [Test]
        public void LoginFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginForm
            //Assert.IsInstanceOfType<LoginForm> (instance, "variable 'instance' is a LoginForm");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'LastElem'
        /// </summary>
        [Test]
        public void LastElemTest()
        {
            // TODO unit test for the property 'LastElem'
        }

    }

}
