/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Login
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginTests
    {
        // TODO uncomment below to declare an instance variable for Login
        //private Login instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Login
            //instance = new Login();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Login
        /// </summary>
        [Test]
        public void LoginInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Login
            //Assert.IsInstanceOfType<Login> (instance, "variable 'instance' is a Login");
        }


        /// <summary>
        /// Test the property 'At'
        /// </summary>
        [Test]
        public void AtTest()
        {
            // TODO unit test for the property 'At'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'TimeOut'
        /// </summary>
        [Test]
        public void TimeOutTest()
        {
            // TODO unit test for the property 'TimeOut'
        }
        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }
        /// <summary>
        /// Test the property 'AccountInfo'
        /// </summary>
        [Test]
        public void AccountInfoTest()
        {
            // TODO unit test for the property 'AccountInfo'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'EntryPoint'
        /// </summary>
        [Test]
        public void EntryPointTest()
        {
            // TODO unit test for the property 'EntryPoint'
        }
        /// <summary>
        /// Test the property 'RequestData'
        /// </summary>
        [Test]
        public void RequestDataTest()
        {
            // TODO unit test for the property 'RequestData'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
