/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginBodyTests
    {
        // TODO uncomment below to declare an instance variable for LoginBody
        //private LoginBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginBody
            //instance = new LoginBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginBody
        /// </summary>
        [Test]
        public void LoginBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginBody
            //Assert.IsInstanceOfType<LoginBody> (instance, "variable 'instance' is a LoginBody");
        }


        /// <summary>
        /// Test the property 'LoginType'
        /// </summary>
        [Test]
        public void LoginTypeTest()
        {
            // TODO unit test for the property 'LoginType'
        }
        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Test]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }
        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Test]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }
        /// <summary>
        /// Test the property 'Pid'
        /// </summary>
        [Test]
        public void PidTest()
        {
            // TODO unit test for the property 'Pid'
        }
        /// <summary>
        /// Test the property 'Cn'
        /// </summary>
        [Test]
        public void CnTest()
        {
            // TODO unit test for the property 'Cn'
        }
        /// <summary>
        /// Test the property 'Sft'
        /// </summary>
        [Test]
        public void SftTest()
        {
            // TODO unit test for the property 'Sft'
        }
        /// <summary>
        /// Test the property 'Scid'
        /// </summary>
        [Test]
        public void ScidTest()
        {
            // TODO unit test for the property 'Scid'
        }
        /// <summary>
        /// Test the property 'UN'
        /// </summary>
        [Test]
        public void UNTest()
        {
            // TODO unit test for the property 'UN'
        }
        /// <summary>
        /// Test the property 'PW'
        /// </summary>
        [Test]
        public void PWTest()
        {
            // TODO unit test for the property 'PW'
        }
        /// <summary>
        /// Test the property 'Lt'
        /// </summary>
        [Test]
        public void LtTest()
        {
            // TODO unit test for the property 'Lt'
        }
        /// <summary>
        /// Test the property 'Pw2'
        /// </summary>
        [Test]
        public void Pw2Test()
        {
            // TODO unit test for the property 'Pw2'
        }
        /// <summary>
        /// Test the property 'Ver'
        /// </summary>
        [Test]
        public void VerTest()
        {
            // TODO unit test for the property 'Ver'
        }

    }

}
