/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoginData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginDataTests
    {
        // TODO uncomment below to declare an instance variable for LoginData
        //private LoginData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginData
            //instance = new LoginData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginData
        /// </summary>
        [Test]
        public void LoginDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginData
            //Assert.IsInstanceOfType<LoginData> (instance, "variable 'instance' is a LoginData");
        }


        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'EsiaLoginPage'
        /// </summary>
        [Test]
        public void EsiaLoginPageTest()
        {
            // TODO unit test for the property 'EsiaLoginPage'
        }
        /// <summary>
        /// Test the property 'CacheVer'
        /// </summary>
        [Test]
        public void CacheVerTest()
        {
            // TODO unit test for the property 'CacheVer'
        }
        /// <summary>
        /// Test the property 'SchoolLogin'
        /// </summary>
        [Test]
        public void SchoolLoginTest()
        {
            // TODO unit test for the property 'SchoolLogin'
        }
        /// <summary>
        /// Test the property 'EmLogin'
        /// </summary>
        [Test]
        public void EmLoginTest()
        {
            // TODO unit test for the property 'EmLogin'
        }
        /// <summary>
        /// Test the property 'WindowsAuth'
        /// </summary>
        [Test]
        public void WindowsAuthTest()
        {
            // TODO unit test for the property 'WindowsAuth'
        }
        /// <summary>
        /// Test the property 'EnableSms'
        /// </summary>
        [Test]
        public void EnableSmsTest()
        {
            // TODO unit test for the property 'EnableSms'
        }
        /// <summary>
        /// Test the property 'EsiaMainAuth'
        /// </summary>
        [Test]
        public void EsiaMainAuthTest()
        {
            // TODO unit test for the property 'EsiaMainAuth'
        }
        /// <summary>
        /// Test the property 'EsiaButton'
        /// </summary>
        [Test]
        public void EsiaButtonTest()
        {
            // TODO unit test for the property 'EsiaButton'
        }
        /// <summary>
        /// Test the property 'SignatureLogin'
        /// </summary>
        [Test]
        public void SignatureLoginTest()
        {
            // TODO unit test for the property 'SignatureLogin'
        }

    }

}
