/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PrepareEmLoginForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PrepareEmLoginFormTests
    {
        // TODO uncomment below to declare an instance variable for PrepareEmLoginForm
        //private PrepareEmLoginForm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrepareEmLoginForm
            //instance = new PrepareEmLoginForm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrepareEmLoginForm
        /// </summary>
        [Test]
        public void PrepareEmLoginFormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PrepareEmLoginForm
            //Assert.IsInstanceOfType<PrepareEmLoginForm> (instance, "variable 'instance' is a PrepareEmLoginForm");
        }


        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Test]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }
        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Test]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }
        /// <summary>
        /// Test the property 'Hlevels'
        /// </summary>
        [Test]
        public void HlevelsTest()
        {
            // TODO unit test for the property 'Hlevels'
        }
        /// <summary>
        /// Test the property 'Ems'
        /// </summary>
        [Test]
        public void EmsTest()
        {
            // TODO unit test for the property 'Ems'
        }
        /// <summary>
        /// Test the property 'EmCid'
        /// </summary>
        [Test]
        public void EmCidTest()
        {
            // TODO unit test for the property 'EmCid'
        }
        /// <summary>
        /// Test the property 'EmSid'
        /// </summary>
        [Test]
        public void EmSidTest()
        {
            // TODO unit test for the property 'EmSid'
        }
        /// <summary>
        /// Test the property 'Hlevel'
        /// </summary>
        [Test]
        public void HlevelTest()
        {
            // TODO unit test for the property 'Hlevel'
        }
        /// <summary>
        /// Test the property 'EmId'
        /// </summary>
        [Test]
        public void EmIdTest()
        {
            // TODO unit test for the property 'EmId'
        }

    }

}
