/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StudentDiaryInit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StudentDiaryInitTests
    {
        // TODO uncomment below to declare an instance variable for StudentDiaryInit
        //private StudentDiaryInit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StudentDiaryInit
            //instance = new StudentDiaryInit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudentDiaryInit
        /// </summary>
        [Test]
        public void StudentDiaryInitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StudentDiaryInit
            //Assert.IsInstanceOfType<StudentDiaryInit> (instance, "variable 'instance' is a StudentDiaryInit");
        }


        /// <summary>
        /// Test the property 'Students'
        /// </summary>
        [Test]
        public void StudentsTest()
        {
            // TODO unit test for the property 'Students'
        }
        /// <summary>
        /// Test the property 'CurrentStudentId'
        /// </summary>
        [Test]
        public void CurrentStudentIdTest()
        {
            // TODO unit test for the property 'CurrentStudentId'
        }
        /// <summary>
        /// Test the property 'WeekStart'
        /// </summary>
        [Test]
        public void WeekStartTest()
        {
            // TODO unit test for the property 'WeekStart'
        }
        /// <summary>
        /// Test the property 'YaClass'
        /// </summary>
        [Test]
        public void YaClassTest()
        {
            // TODO unit test for the property 'YaClass'
        }
        /// <summary>
        /// Test the property 'YaClassAuthUrl'
        /// </summary>
        [Test]
        public void YaClassAuthUrlTest()
        {
            // TODO unit test for the property 'YaClassAuthUrl'
        }
        /// <summary>
        /// Test the property 'NewDiskToken'
        /// </summary>
        [Test]
        public void NewDiskTokenTest()
        {
            // TODO unit test for the property 'NewDiskToken'
        }
        /// <summary>
        /// Test the property 'NewDiskWasRequest'
        /// </summary>
        [Test]
        public void NewDiskWasRequestTest()
        {
            // TODO unit test for the property 'NewDiskWasRequest'
        }
        /// <summary>
        /// Test the property 'TtsuRl'
        /// </summary>
        [Test]
        public void TtsuRlTest()
        {
            // TODO unit test for the property 'TtsuRl'
        }
        /// <summary>
        /// Test the property 'ExternalUrl'
        /// </summary>
        [Test]
        public void ExternalUrlTest()
        {
            // TODO unit test for the property 'ExternalUrl'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'MaxMark'
        /// </summary>
        [Test]
        public void MaxMarkTest()
        {
            // TODO unit test for the property 'MaxMark'
        }
        /// <summary>
        /// Test the property 'WithLaAssigns'
        /// </summary>
        [Test]
        public void WithLaAssignsTest()
        {
            // TODO unit test for the property 'WithLaAssigns'
        }

    }

}
