# coding: utf-8

"""
    NetSchool

    The API for the NetSchool irTech project  # noqa: E501

    OpenAPI spec version: 4.30.43656
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.prepare_login_form import PrepareLoginForm  # noqa: E501
from swagger_client.rest import ApiException


class TestPrepareLoginForm(unittest.TestCase):
    """PrepareLoginForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrepareLoginForm(self):
        """Test PrepareLoginForm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.prepare_login_form.PrepareLoginForm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
