# coding: utf-8

"""
    NetSchool

    The API for the NetSchool irTech project  # noqa: E501

    OpenAPI spec version: 5.10.63221
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.login_account_info_user import LoginAccountInfoUser  # noqa: E501
from swagger_client.rest import ApiException


class TestLoginAccountInfoUser(unittest.TestCase):
    """LoginAccountInfoUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginAccountInfoUser(self):
        """Test LoginAccountInfoUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.login_account_info_user.LoginAccountInfoUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
