# coding: utf-8

"""
    NetSchool

    The API for the NetSchool irTech project  # noqa: E501

    OpenAPI spec version: 4.30.43656
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.prepare_em_login_form_countries import PrepareEmLoginFormCountries  # noqa: E501
from swagger_client.rest import ApiException


class TestPrepareEmLoginFormCountries(unittest.TestCase):
    """PrepareEmLoginFormCountries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrepareEmLoginFormCountries(self):
        """Test PrepareEmLoginFormCountries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.prepare_em_login_form_countries.PrepareEmLoginFormCountries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
