/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NetSchool);
  }
}(this, function(expect, NetSchool) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetAuthData', function() {
      beforeEach(function() {
        instance = new NetSchool.GetAuthData();
      });

      it('should create an instance of GetAuthData', function() {
        // TODO: update the code to test GetAuthData
        expect(instance).to.be.a(NetSchool.GetAuthData);
      });

      it('should have the property lt (base name: "lt")', function() {
        // TODO: update the code to test the property lt
        expect(instance).to.have.property('lt');
        // expect(instance.lt).to.be(expectedValueLiteral);
      });

      it('should have the property ver (base name: "ver")', function() {
        // TODO: update the code to test the property ver
        expect(instance).to.have.property('ver');
        // expect(instance.ver).to.be(expectedValueLiteral);
      });

      it('should have the property salt (base name: "salt")', function() {
        // TODO: update the code to test the property salt
        expect(instance).to.have.property('salt');
        // expect(instance.salt).to.be(expectedValueLiteral);
      });

    });
  });

}));
