/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NetSchool);
  }
}(this, function(expect, NetSchool) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PrepareEmLoginForm', function() {
      beforeEach(function() {
        instance = new NetSchool.PrepareEmLoginForm();
      });

      it('should create an instance of PrepareEmLoginForm', function() {
        // TODO: update the code to test PrepareEmLoginForm
        expect(instance).to.be.a(NetSchool.PrepareEmLoginForm);
      });

      it('should have the property countries (base name: "countries")', function() {
        // TODO: update the code to test the property countries
        expect(instance).to.have.property('countries');
        // expect(instance.countries).to.be(expectedValueLiteral);
      });

      it('should have the property states (base name: "states")', function() {
        // TODO: update the code to test the property states
        expect(instance).to.have.property('states');
        // expect(instance.states).to.be(expectedValueLiteral);
      });

      it('should have the property hlevels (base name: "hlevels")', function() {
        // TODO: update the code to test the property hlevels
        expect(instance).to.have.property('hlevels');
        // expect(instance.hlevels).to.be(expectedValueLiteral);
      });

      it('should have the property ems (base name: "ems")', function() {
        // TODO: update the code to test the property ems
        expect(instance).to.have.property('ems');
        // expect(instance.ems).to.be(expectedValueLiteral);
      });

      it('should have the property emCid (base name: "em_cid")', function() {
        // TODO: update the code to test the property emCid
        expect(instance).to.have.property('emCid');
        // expect(instance.emCid).to.be(expectedValueLiteral);
      });

      it('should have the property emSid (base name: "em_sid")', function() {
        // TODO: update the code to test the property emSid
        expect(instance).to.have.property('emSid');
        // expect(instance.emSid).to.be(expectedValueLiteral);
      });

      it('should have the property hlevel (base name: "hlevel")', function() {
        // TODO: update the code to test the property hlevel
        expect(instance).to.have.property('hlevel');
        // expect(instance.hlevel).to.be(expectedValueLiteral);
      });

      it('should have the property emId (base name: "emId")', function() {
        // TODO: update the code to test the property emId
        expect(instance).to.have.property('emId');
        // expect(instance.emId).to.be(expectedValueLiteral);
      });

    });
  });

}));
