<?php
/**
 * PrepareLoginFormTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PrepareLoginFormTest Class Doc Comment
 *
 * @category    Class
 * @description PrepareLoginForm
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PrepareLoginFormTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PrepareLoginForm"
     */
    public function testPrepareLoginForm()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "states"
     */
    public function testPropertyStates()
    {
    }

    /**
     * Test attribute "provinces"
     */
    public function testPropertyProvinces()
    {
    }

    /**
     * Test attribute "cities"
     */
    public function testPropertyCities()
    {
    }

    /**
     * Test attribute "funcs"
     */
    public function testPropertyFuncs()
    {
    }

    /**
     * Test attribute "schools"
     */
    public function testPropertySchools()
    {
    }

    /**
     * Test attribute "cid"
     */
    public function testPropertyCid()
    {
    }

    /**
     * Test attribute "sid"
     */
    public function testPropertySid()
    {
    }

    /**
     * Test attribute "pid"
     */
    public function testPropertyPid()
    {
    }

    /**
     * Test attribute "cn"
     */
    public function testPropertyCn()
    {
    }

    /**
     * Test attribute "sft"
     */
    public function testPropertySft()
    {
    }

    /**
     * Test attribute "scid"
     */
    public function testPropertyScid()
    {
    }

    /**
     * Test attribute "hlevels"
     */
    public function testPropertyHlevels()
    {
    }

    /**
     * Test attribute "ems"
     */
    public function testPropertyEms()
    {
    }
}
