<?php
/**
 * StudentDiaryInitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StudentDiaryInitTest Class Doc Comment
 *
 * @category    Class
 * @description StudentDiaryInit
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StudentDiaryInitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StudentDiaryInit"
     */
    public function testStudentDiaryInit()
    {
    }

    /**
     * Test attribute "students"
     */
    public function testPropertyStudents()
    {
    }

    /**
     * Test attribute "current_student_id"
     */
    public function testPropertyCurrentStudentId()
    {
    }

    /**
     * Test attribute "week_start"
     */
    public function testPropertyWeekStart()
    {
    }

    /**
     * Test attribute "ya_class"
     */
    public function testPropertyYaClass()
    {
    }

    /**
     * Test attribute "ya_class_auth_url"
     */
    public function testPropertyYaClassAuthUrl()
    {
    }

    /**
     * Test attribute "new_disk_token"
     */
    public function testPropertyNewDiskToken()
    {
    }

    /**
     * Test attribute "new_disk_was_request"
     */
    public function testPropertyNewDiskWasRequest()
    {
    }

    /**
     * Test attribute "ttsu_rl"
     */
    public function testPropertyTtsuRl()
    {
    }

    /**
     * Test attribute "external_url"
     */
    public function testPropertyExternalUrl()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "max_mark"
     */
    public function testPropertyMaxMark()
    {
    }

    /**
     * Test attribute "with_la_assigns"
     */
    public function testPropertyWithLaAssigns()
    {
    }
}
