/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AssignmentTypesInner model module.
 * @module model/AssignmentTypesInner
 * @version 5.10.63221
 */
export class AssignmentTypesInner {
  /**
   * Constructs a new <code>AssignmentTypesInner</code>.
   * @alias module:model/AssignmentTypesInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AssignmentTypesInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssignmentTypesInner} obj Optional instance to populate.
   * @return {module:model/AssignmentTypesInner} The populated <code>AssignmentTypesInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AssignmentTypesInner();
      if (data.hasOwnProperty('abbr'))
        obj.abbr = ApiClient.convertToType(data['abbr'], 'String');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} abbr
 */
AssignmentTypesInner.prototype.abbr = undefined;

/**
 * @member {Number} order
 */
AssignmentTypesInner.prototype.order = undefined;

/**
 * @member {Number} id
 */
AssignmentTypesInner.prototype.id = undefined;

/**
 * @member {String} name
 */
AssignmentTypesInner.prototype.name = undefined;

