/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DiaryAssignDetailsAttachments model module.
 * @module model/DiaryAssignDetailsAttachments
 * @version 5.10.63221
 */
export class DiaryAssignDetailsAttachments {
  /**
   * Constructs a new <code>DiaryAssignDetailsAttachments</code>.
   * @alias module:model/DiaryAssignDetailsAttachments
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DiaryAssignDetailsAttachments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DiaryAssignDetailsAttachments} obj Optional instance to populate.
   * @return {module:model/DiaryAssignDetailsAttachments} The populated <code>DiaryAssignDetailsAttachments</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DiaryAssignDetailsAttachments();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('originalFileName'))
        obj.originalFileName = ApiClient.convertToType(data['originalFileName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DiaryAssignDetailsAttachments.prototype.id = undefined;

/**
 * @member {String} name
 */
DiaryAssignDetailsAttachments.prototype.name = undefined;

/**
 * @member {String} originalFileName
 */
DiaryAssignDetailsAttachments.prototype.originalFileName = undefined;

/**
 * @member {String} description
 */
DiaryAssignDetailsAttachments.prototype.description = undefined;

