/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetAuthData model module.
 * @module model/GetAuthData
 * @version 5.10.63221
 */
export class GetAuthData {
  /**
   * Constructs a new <code>GetAuthData</code>.
   * @alias module:model/GetAuthData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetAuthData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAuthData} obj Optional instance to populate.
   * @return {module:model/GetAuthData} The populated <code>GetAuthData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetAuthData();
      if (data.hasOwnProperty('lt'))
        obj.lt = ApiClient.convertToType(data['lt'], 'String');
      if (data.hasOwnProperty('ver'))
        obj.ver = ApiClient.convertToType(data['ver'], 'String');
      if (data.hasOwnProperty('salt'))
        obj.salt = ApiClient.convertToType(data['salt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} lt
 */
GetAuthData.prototype.lt = undefined;

/**
 * @member {String} ver
 */
GetAuthData.prototype.ver = undefined;

/**
 * @member {String} salt
 */
GetAuthData.prototype.salt = undefined;

