/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoginBody model module.
 * @module model/LoginBody
 * @version 5.10.63221
 */
export class LoginBody {
  /**
   * Constructs a new <code>LoginBody</code>.
   * @alias module:model/LoginBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoginBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginBody} obj Optional instance to populate.
   * @return {module:model/LoginBody} The populated <code>LoginBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginBody();
      if (data.hasOwnProperty('LoginType'))
        obj.loginType = ApiClient.convertToType(data['LoginType'], 'Number');
      if (data.hasOwnProperty('cid'))
        obj.cid = ApiClient.convertToType(data['cid'], 'Number');
      if (data.hasOwnProperty('sid'))
        obj.sid = ApiClient.convertToType(data['sid'], 'Number');
      if (data.hasOwnProperty('pid'))
        obj.pid = ApiClient.convertToType(data['pid'], 'Number');
      if (data.hasOwnProperty('cn'))
        obj.cn = ApiClient.convertToType(data['cn'], 'Number');
      if (data.hasOwnProperty('sft'))
        obj.sft = ApiClient.convertToType(data['sft'], 'Number');
      if (data.hasOwnProperty('scid'))
        obj.scid = ApiClient.convertToType(data['scid'], 'Number');
      if (data.hasOwnProperty('UN'))
        obj.UN = ApiClient.convertToType(data['UN'], 'String');
      if (data.hasOwnProperty('PW'))
        obj.PW = ApiClient.convertToType(data['PW'], 'String');
      if (data.hasOwnProperty('lt'))
        obj.lt = ApiClient.convertToType(data['lt'], 'Number');
      if (data.hasOwnProperty('pw2'))
        obj.pw2 = ApiClient.convertToType(data['pw2'], 'String');
      if (data.hasOwnProperty('ver'))
        obj.ver = ApiClient.convertToType(data['ver'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} loginType
 */
LoginBody.prototype.loginType = undefined;

/**
 * @member {Number} cid
 */
LoginBody.prototype.cid = undefined;

/**
 * @member {Number} sid
 */
LoginBody.prototype.sid = undefined;

/**
 * @member {Number} pid
 */
LoginBody.prototype.pid = undefined;

/**
 * @member {Number} cn
 */
LoginBody.prototype.cn = undefined;

/**
 * @member {Number} sft
 */
LoginBody.prototype.sft = undefined;

/**
 * @member {Number} scid
 */
LoginBody.prototype.scid = undefined;

/**
 * @member {String} UN
 */
LoginBody.prototype.UN = undefined;

/**
 * @member {String} PW
 */
LoginBody.prototype.PW = undefined;

/**
 * @member {Number} lt
 */
LoginBody.prototype.lt = undefined;

/**
 * @member {String} pw2
 */
LoginBody.prototype.pw2 = undefined;

/**
 * @member {Number} ver
 */
LoginBody.prototype.ver = undefined;

