/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoginRequestData model module.
 * @module model/LoginRequestData
 * @version 5.10.63221
 */
export class LoginRequestData {
  /**
   * Constructs a new <code>LoginRequestData</code>.
   * @alias module:model/LoginRequestData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoginRequestData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginRequestData} obj Optional instance to populate.
   * @return {module:model/LoginRequestData} The populated <code>LoginRequestData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginRequestData();
      if (data.hasOwnProperty('warnType'))
        obj.warnType = ApiClient.convertToType(data['warnType'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} warnType
 */
LoginRequestData.prototype.warnType = undefined;

