/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Mark model module.
 * @module model/Mark
 * @version 5.10.63221
 */
export class Mark {
  /**
   * Constructs a new <code>Mark</code>.
   * @alias module:model/Mark
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Mark</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Mark} obj Optional instance to populate.
   * @return {module:model/Mark} The populated <code>Mark</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Mark();
      if (data.hasOwnProperty('assignmentId'))
        obj.assignmentId = ApiClient.convertToType(data['assignmentId'], 'Number');
      if (data.hasOwnProperty('studentId'))
        obj.studentId = ApiClient.convertToType(data['studentId'], 'Number');
      if (data.hasOwnProperty('mark'))
        obj.mark = ApiClient.convertToType(data['mark'], 'Number');
      if (data.hasOwnProperty('dutyMark'))
        obj.dutyMark = ApiClient.convertToType(data['dutyMark'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} assignmentId
 */
Mark.prototype.assignmentId = undefined;

/**
 * @member {Number} studentId
 */
Mark.prototype.studentId = undefined;

/**
 * @member {Number} mark
 */
Mark.prototype.mark = undefined;

/**
 * @member {Boolean} dutyMark
 */
Mark.prototype.dutyMark = undefined;

