/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MySettingsUserSettings} from './MySettingsUserSettings';

/**
 * The MySettings model module.
 * @module model/MySettings
 * @version 5.10.63221
 */
export class MySettings {
  /**
   * Constructs a new <code>MySettings</code>.
   * @alias module:model/MySettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MySettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MySettings} obj Optional instance to populate.
   * @return {module:model/MySettings} The populated <code>MySettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MySettings();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('middleName'))
        obj.middleName = ApiClient.convertToType(data['middleName'], 'String');
      if (data.hasOwnProperty('loginName'))
        obj.loginName = ApiClient.convertToType(data['loginName'], 'String');
      if (data.hasOwnProperty('birthDate'))
        obj.birthDate = ApiClient.convertToType(data['birthDate'], 'Date');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], ['String']);
      if (data.hasOwnProperty('schoolyearId'))
        obj.schoolyearId = ApiClient.convertToType(data['schoolyearId'], 'Number');
      if (data.hasOwnProperty('windowsAccount'))
        obj.windowsAccount = ApiClient.convertToType(data['windowsAccount'], 'String');
      if (data.hasOwnProperty('mobilePhone'))
        obj.mobilePhone = ApiClient.convertToType(data['mobilePhone'], 'String');
      if (data.hasOwnProperty('preferedCom'))
        obj.preferedCom = ApiClient.convertToType(data['preferedCom'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('existsPhoto'))
        obj.existsPhoto = ApiClient.convertToType(data['existsPhoto'], 'Boolean');
      if (data.hasOwnProperty('userSettings'))
        obj.userSettings = MySettingsUserSettings.constructFromObject(data['userSettings']);
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
MySettings.prototype.userId = undefined;

/**
 * @member {String} firstName
 */
MySettings.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
MySettings.prototype.lastName = undefined;

/**
 * @member {String} middleName
 */
MySettings.prototype.middleName = undefined;

/**
 * @member {String} loginName
 */
MySettings.prototype.loginName = undefined;

/**
 * @member {Date} birthDate
 */
MySettings.prototype.birthDate = undefined;

/**
 * @member {Array.<String>} roles
 */
MySettings.prototype.roles = undefined;

/**
 * @member {Number} schoolyearId
 */
MySettings.prototype.schoolyearId = undefined;

/**
 * @member {String} windowsAccount
 */
MySettings.prototype.windowsAccount = undefined;

/**
 * @member {String} mobilePhone
 */
MySettings.prototype.mobilePhone = undefined;

/**
 * @member {String} preferedCom
 */
MySettings.prototype.preferedCom = undefined;

/**
 * @member {String} email
 */
MySettings.prototype.email = undefined;

/**
 * @member {Boolean} existsPhoto
 */
MySettings.prototype.existsPhoto = undefined;

/**
 * @member {module:model/MySettingsUserSettings} userSettings
 */
MySettings.prototype.userSettings = undefined;

