/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.DiaryAssignDetailsAttachments
import io.swagger.client.models.DiaryAssignDetailsSubjectGroup
import io.swagger.client.models.DiaryAssignDetailsTeachers

/**
 * 
 * @param id 
 * @param assignmentName 
 * @param activityName 
 * @param problemName 
 * @param subjectGroup 
 * @param teachers 
 * @param productId 
 * @param isDeleted 
 * @param weight 
 * @param date 
 * @param description 
 * @param attachments 
 * @param contentElements 
 * @param codeContentElements 
 */
data class DiaryAssignDetails (

    val id: kotlin.Int? = null,
    val assignmentName: kotlin.String? = null,
    val activityName: kotlin.String? = null,
    val problemName: kotlin.String? = null,
    val subjectGroup: DiaryAssignDetailsSubjectGroup? = null,
    val teachers: kotlin.Array<DiaryAssignDetailsTeachers>? = null,
    val productId: kotlin.Int? = null,
    val isDeleted: kotlin.Boolean? = null,
    val weight: kotlin.Int? = null,
    val date: java.time.LocalDate? = null,
    val description: kotlin.String? = null,
    val attachments: kotlin.Array<DiaryAssignDetailsAttachments>? = null,
    val contentElements: kotlin.Array<kotlin.Any>? = null,
    val codeContentElements: kotlin.Array<kotlin.Any>? = null
) {
}