/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.DiaryWeekDays

/**
 * 
 * @param weekStart 
 * @param weekEnd 
 * @param weekDays 
 * @param termName 
 * @param className 
 */
data class Diary (

    val weekStart: kotlin.String? = null,
    val weekEnd: kotlin.String? = null,
    val weekDays: kotlin.Array<DiaryWeekDays>? = null,
    val termName: kotlin.String? = null,
    val className: kotlin.String? = null
) {
}