/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.LoginAccountInfoCurrentOrganization
import io.swagger.client.models.LoginAccountInfoOrganizations
import io.swagger.client.models.LoginAccountInfoUser
import io.swagger.client.models.LoginAccountInfoUserRoles

/**
 * 
 * @param activeToken 
 * @param secureActiveToken 
 * @param currentOrganization 
 * @param user 
 * @param userRoles 
 * @param organizations 
 * @param loginTime 
 * @param active 
 * @param canLogin 
 * @param storeTokens 
 * @param accessToken 
 */
data class LoginAccountInfo (

    val activeToken: kotlin.String? = null,
    val secureActiveToken: kotlin.String? = null,
    val currentOrganization: LoginAccountInfoCurrentOrganization? = null,
    val user: LoginAccountInfoUser? = null,
    val userRoles: LoginAccountInfoUserRoles? = null,
    val organizations: kotlin.Array<LoginAccountInfoOrganizations>? = null,
    val loginTime: java.time.LocalDate? = null,
    val active: kotlin.Boolean? = null,
    val canLogin: kotlin.Boolean? = null,
    val storeTokens: kotlin.Boolean? = null,
    val accessToken: kotlin.String? = null
) {
}