/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param productName 
 * @param version 
 * @param schoolLogin 
 * @param emLogin 
 * @param esiaLogin 
 * @param esiaLoginPage 
 * @param esiaMainAuth 
 * @param esiaButton 
 * @param signatureLogin 
 * @param cacheVer 
 * @param windowsAuth 
 * @param enableSms 
 * @param esaLogin 
 * @param esaLoginPage 
 */
data class LoginData (

    val productName: kotlin.String? = null,
    val version: kotlin.String? = null,
    val schoolLogin: kotlin.Boolean? = null,
    val emLogin: kotlin.Boolean? = null,
    val esiaLogin: kotlin.Boolean? = null,
    val esiaLoginPage: kotlin.String? = null,
    val esiaMainAuth: kotlin.Boolean? = null,
    val esiaButton: kotlin.Boolean? = null,
    val signatureLogin: kotlin.Boolean? = null,
    val cacheVer: kotlin.String? = null,
    val windowsAuth: kotlin.Boolean? = null,
    val enableSms: kotlin.Boolean? = null,
    val esaLogin: kotlin.Boolean? = null,
    val esaLoginPage: kotlin.String? = null
) {
}