/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MySettingsUserSettings

/**
 * 
 * @param userId 
 * @param firstName 
 * @param lastName 
 * @param middleName 
 * @param loginName 
 * @param birthDate 
 * @param roles 
 * @param schoolyearId 
 * @param windowsAccount 
 * @param mobilePhone 
 * @param preferedCom 
 * @param email 
 * @param existsPhoto 
 * @param userSettings 
 */
data class MySettings (

    val userId: kotlin.Int? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val middleName: kotlin.String? = null,
    val loginName: kotlin.String? = null,
    val birthDate: java.time.LocalDate? = null,
    val roles: kotlin.Array<kotlin.String>? = null,
    val schoolyearId: kotlin.Int? = null,
    val windowsAccount: kotlin.String? = null,
    val mobilePhone: kotlin.String? = null,
    val preferedCom: kotlin.String? = null,
    val email: kotlin.String? = null,
    val existsPhoto: kotlin.Boolean? = null,
    val userSettings: MySettingsUserSettings? = null
) {
}