/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param studentId 
 * @param nickName 
 * @param className 
 * @param classId 
 * @param iupGrade 
 */
data class StudentDiaryInitStudents (

    val studentId: kotlin.Int? = null,
    val nickName: kotlin.String? = null,
    val className: kotlin.Any? = null,
    val classId: kotlin.Int? = null,
    val iupGrade: kotlin.Int? = null
) {
}