/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param abbr  for example: '''ДЗ'''
 * @param order  for example: '''15'''
 * @param id  for example: '''3'''
 * @param name  for example: '''Домашнее задание'''
 */
case class AssignmentTypesInner (
  abbr: Option[String] = None,
  order: Option[Integer] = None,
  id: Option[Integer] = None,
  name: Option[String] = None
)

