/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param activeToken 
 * @param secureActiveToken 
 * @param currentOrganization 
 * @param user 
 * @param userRoles 
 * @param organizations 
 * @param loginTime 
 * @param active  for example: '''true'''
 * @param canLogin  for example: '''true'''
 * @param storeTokens  for example: '''true'''
 * @param accessToken  for example: '''00168638015429814024329375'''
 */
case class LoginAccountInfo (
  activeToken: Option[String] = None,
  secureActiveToken: Option[String] = None,
  currentOrganization: Option[Login_accountInfo_currentOrganization] = None,
  user: Option[Login_accountInfo_user] = None,
  userRoles: Option[Login_accountInfo_userRoles] = None,
  organizations: Option[List[Login_accountInfo_organizations]] = None,
  loginTime: Option[date] = None,
  active: Option[Boolean] = None,
  canLogin: Option[Boolean] = None,
  storeTokens: Option[Boolean] = None,
  accessToken: Option[String] = None
)

