/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param id  for example: '''22'''
 * @param name  for example: '''МБОУ СОШ №19 (г. Екатеринбург) '''
 */
case class LoginAccountInfoOrganizations (
  id: Option[Integer] = None,
  name: Option[String] = None
)

