/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param countries 
 * @param states 
 * @param hlevels 
 * @param ems 
 * @param emCid 
 * @param emSid 
 * @param hlevel 
 * @param emId 
 */
case class PrepareEmLoginForm (
  countries: Option[List[PrepareEmLoginForm_countries]] = None,
  states: Option[List[PrepareEmLoginForm_countries]] = None,
  hlevels: Option[List[PrepareEmLoginForm_countries]] = None,
  ems: Option[List[PrepareEmLoginForm_countries]] = None,
  emCid: Option[Integer] = None,
  emSid: Option[Integer] = None,
  hlevel: Option[Integer] = None,
  emId: Option[Integer] = None
)

