=begin
#NetSchool

#The API for the NetSchool irTech project

OpenAPI spec version: 5.10.63221

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

require 'date'

module SwaggerClient
  class LoginData
    attr_accessor :product_name

    attr_accessor :version

    attr_accessor :school_login

    attr_accessor :em_login

    attr_accessor :esia_login

    attr_accessor :esia_login_page

    attr_accessor :esia_main_auth

    attr_accessor :esia_button

    attr_accessor :signature_login

    attr_accessor :cache_ver

    attr_accessor :windows_auth

    attr_accessor :enable_sms

    attr_accessor :esa_login

    attr_accessor :esa_login_page

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'product_name' => :'productName',
        :'version' => :'version',
        :'school_login' => :'schoolLogin',
        :'em_login' => :'emLogin',
        :'esia_login' => :'esiaLogin',
        :'esia_login_page' => :'esiaLoginPage',
        :'esia_main_auth' => :'esiaMainAuth',
        :'esia_button' => :'esiaButton',
        :'signature_login' => :'signatureLogin',
        :'cache_ver' => :'cacheVer',
        :'windows_auth' => :'windowsAuth',
        :'enable_sms' => :'enableSms',
        :'esa_login' => :'esaLogin',
        :'esa_login_page' => :'esaLoginPage'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'product_name' => :'Object',
        :'version' => :'Object',
        :'school_login' => :'Object',
        :'em_login' => :'Object',
        :'esia_login' => :'Object',
        :'esia_login_page' => :'Object',
        :'esia_main_auth' => :'Object',
        :'esia_button' => :'Object',
        :'signature_login' => :'Object',
        :'cache_ver' => :'Object',
        :'windows_auth' => :'Object',
        :'enable_sms' => :'Object',
        :'esa_login' => :'Object',
        :'esa_login_page' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SwaggerClient::LoginData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SwaggerClient::LoginData`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'product_name')
        self.product_name = attributes[:'product_name']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.key?(:'school_login')
        self.school_login = attributes[:'school_login']
      end

      if attributes.key?(:'em_login')
        self.em_login = attributes[:'em_login']
      end

      if attributes.key?(:'esia_login')
        self.esia_login = attributes[:'esia_login']
      end

      if attributes.key?(:'esia_login_page')
        self.esia_login_page = attributes[:'esia_login_page']
      end

      if attributes.key?(:'esia_main_auth')
        self.esia_main_auth = attributes[:'esia_main_auth']
      end

      if attributes.key?(:'esia_button')
        self.esia_button = attributes[:'esia_button']
      end

      if attributes.key?(:'signature_login')
        self.signature_login = attributes[:'signature_login']
      end

      if attributes.key?(:'cache_ver')
        self.cache_ver = attributes[:'cache_ver']
      end

      if attributes.key?(:'windows_auth')
        self.windows_auth = attributes[:'windows_auth']
      end

      if attributes.key?(:'enable_sms')
        self.enable_sms = attributes[:'enable_sms']
      end

      if attributes.key?(:'esa_login')
        self.esa_login = attributes[:'esa_login']
      end

      if attributes.key?(:'esa_login_page')
        self.esa_login_page = attributes[:'esa_login_page']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          product_name == o.product_name &&
          version == o.version &&
          school_login == o.school_login &&
          em_login == o.em_login &&
          esia_login == o.esia_login &&
          esia_login_page == o.esia_login_page &&
          esia_main_auth == o.esia_main_auth &&
          esia_button == o.esia_button &&
          signature_login == o.signature_login &&
          cache_ver == o.cache_ver &&
          windows_auth == o.windows_auth &&
          enable_sms == o.enable_sms &&
          esa_login == o.esa_login &&
          esa_login_page == o.esa_login_page
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [product_name, version, school_login, em_login, esia_login, esia_login_page, esia_main_auth, esia_button, signature_login, cache_ver, windows_auth, enable_sms, esa_login, esa_login_page].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SwaggerClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
