/**
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 4.30.43656
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.LoginData
import io.swagger.client.model.PrepareEmLoginForm
import io.swagger.client.model.PrepareLoginForm
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class LoginApi(
  val defBasePath: String = "https://virtserver.swaggerhub.com/LEBEDEVKM/NetSchool/4.30.43656",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new LoginApiAsyncHelper(client, config)

  /**
   * 
   * returns all login data
   *
   * @return LoginData
   */
  def logindata(): Option[LoginData] = {
    val await = Try(Await.result(logindataAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   *  asynchronously
   * returns all login data
   *
   * @return Future(LoginData)
   */
  def logindataAsync(): Future[LoginData] = {
      helper.logindata()
  }

  /**
   * 
   * returns all prepareemloginform
   *
   * @param cacheVer  (optional)
   * @return PrepareEmLoginForm
   */
  def prepareemloginform(cacheVer: Option[String] = None): Option[PrepareEmLoginForm] = {
    val await = Try(Await.result(prepareemloginformAsync(cacheVer), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   *  asynchronously
   * returns all prepareemloginform
   *
   * @param cacheVer  (optional)
   * @return Future(PrepareEmLoginForm)
   */
  def prepareemloginformAsync(cacheVer: Option[String] = None): Future[PrepareEmLoginForm] = {
      helper.prepareemloginform(cacheVer)
  }

  /**
   * 
   * returns all prepareloginform
   *
   * @param cacheVer  (optional)
   * @return PrepareLoginForm
   */
  def prepareloginform(cacheVer: Option[String] = None): Option[PrepareLoginForm] = {
    val await = Try(Await.result(prepareloginformAsync(cacheVer), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   *  asynchronously
   * returns all prepareloginform
   *
   * @param cacheVer  (optional)
   * @return Future(PrepareLoginForm)
   */
  def prepareloginformAsync(cacheVer: Option[String] = None): Future[PrepareLoginForm] = {
      helper.prepareloginform(cacheVer)
  }

}

class LoginApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def logindata()(implicit reader: ClientResponseReader[LoginData]): Future[LoginData] = {
    // create path and map variables
    val path = (addFmt("/logindata"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def prepareemloginform(cacheVer: Option[String] = None
    )(implicit reader: ClientResponseReader[PrepareEmLoginForm]): Future[PrepareEmLoginForm] = {
    // create path and map variables
    val path = (addFmt("/prepareemloginform"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    cacheVer match {
      case Some(param) => queryParams += "cacheVer" -> param.toString
      case _ => queryParams
    }

    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def prepareloginform(cacheVer: Option[String] = None
    )(implicit reader: ClientResponseReader[PrepareLoginForm]): Future[PrepareLoginForm] = {
    // create path and map variables
    val path = (addFmt("/prepareloginform"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    cacheVer match {
      case Some(param) => queryParams += "cacheVer" -> param.toString
      case _ => queryParams
    }

    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
