/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DiaryWeekDays;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Diary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-16T17:55:39.713Z[GMT]")
public class Diary {
  @SerializedName("weekStart")
  private String weekStart = null;

  @SerializedName("weekEnd")
  private String weekEnd = null;

  @SerializedName("weekDays")
  private List<DiaryWeekDays> weekDays = null;

  @SerializedName("termName")
  private String termName = null;

  @SerializedName("className")
  private String className = null;

  public Diary weekStart(String weekStart) {
    this.weekStart = weekStart;
    return this;
  }

   /**
   * Get weekStart
   * @return weekStart
  **/
  @Schema(description = "")
  public String getWeekStart() {
    return weekStart;
  }

  public void setWeekStart(String weekStart) {
    this.weekStart = weekStart;
  }

  public Diary weekEnd(String weekEnd) {
    this.weekEnd = weekEnd;
    return this;
  }

   /**
   * Get weekEnd
   * @return weekEnd
  **/
  @Schema(description = "")
  public String getWeekEnd() {
    return weekEnd;
  }

  public void setWeekEnd(String weekEnd) {
    this.weekEnd = weekEnd;
  }

  public Diary weekDays(List<DiaryWeekDays> weekDays) {
    this.weekDays = weekDays;
    return this;
  }

  public Diary addWeekDaysItem(DiaryWeekDays weekDaysItem) {
    if (this.weekDays == null) {
      this.weekDays = new ArrayList<DiaryWeekDays>();
    }
    this.weekDays.add(weekDaysItem);
    return this;
  }

   /**
   * Get weekDays
   * @return weekDays
  **/
  @Schema(description = "")
  public List<DiaryWeekDays> getWeekDays() {
    return weekDays;
  }

  public void setWeekDays(List<DiaryWeekDays> weekDays) {
    this.weekDays = weekDays;
  }

  public Diary termName(String termName) {
    this.termName = termName;
    return this;
  }

   /**
   * Get termName
   * @return termName
  **/
  @Schema(description = "")
  public String getTermName() {
    return termName;
  }

  public void setTermName(String termName) {
    this.termName = termName;
  }

  public Diary className(String className) {
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @Schema(description = "")
  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Diary diary = (Diary) o;
    return Objects.equals(this.weekStart, diary.weekStart) &&
        Objects.equals(this.weekEnd, diary.weekEnd) &&
        Objects.equals(this.weekDays, diary.weekDays) &&
        Objects.equals(this.termName, diary.termName) &&
        Objects.equals(this.className, diary.className);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weekStart, weekEnd, weekDays, termName, className);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Diary {\n");
    
    sb.append("    weekStart: ").append(toIndentedString(weekStart)).append("\n");
    sb.append("    weekEnd: ").append(toIndentedString(weekEnd)).append("\n");
    sb.append("    weekDays: ").append(toIndentedString(weekDays)).append("\n");
    sb.append("    termName: ").append(toIndentedString(termName)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
