/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DiaryLesson;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
/**
 * DiaryWeekDays
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-06T08:52:10.951Z[GMT]")
public class DiaryWeekDays {
  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("lessons")
  private List<DiaryLesson> lessons = null;

  public DiaryWeekDays date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @Schema(description = "")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public DiaryWeekDays lessons(List<DiaryLesson> lessons) {
    this.lessons = lessons;
    return this;
  }

  public DiaryWeekDays addLessonsItem(DiaryLesson lessonsItem) {
    if (this.lessons == null) {
      this.lessons = new ArrayList<DiaryLesson>();
    }
    this.lessons.add(lessonsItem);
    return this;
  }

   /**
   * Get lessons
   * @return lessons
  **/
  @Schema(description = "")
  public List<DiaryLesson> getLessons() {
    return lessons;
  }

  public void setLessons(List<DiaryLesson> lessons) {
    this.lessons = lessons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiaryWeekDays diaryWeekDays = (DiaryWeekDays) o;
    return Objects.equals(this.date, diaryWeekDays.date) &&
        Objects.equals(this.lessons, diaryWeekDays.lessons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, lessons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiaryWeekDays {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    lessons: ").append(toIndentedString(lessons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
