/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LoginBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-24T12:37:15.210Z[GMT]")
public class LoginBody {
  @SerializedName("LoginType")
  private Integer loginType = null;

  @SerializedName("cid")
  private Integer cid = null;

  @SerializedName("sid")
  private Integer sid = null;

  @SerializedName("pid")
  private Integer pid = null;

  @SerializedName("cn")
  private Integer cn = null;

  @SerializedName("sft")
  private Integer sft = null;

  @SerializedName("scid")
  private Integer scid = null;

  @SerializedName("UN")
  private String UN = null;

  @SerializedName("PW")
  private String PW = null;

  @SerializedName("lt")
  private Integer lt = null;

  @SerializedName("pw2")
  private String pw2 = null;

  @SerializedName("ver")
  private Integer ver = null;

  public LoginBody loginType(Integer loginType) {
    this.loginType = loginType;
    return this;
  }

   /**
   * Get loginType
   * @return loginType
  **/
  @Schema(example = "1", description = "")
  public Integer getLoginType() {
    return loginType;
  }

  public void setLoginType(Integer loginType) {
    this.loginType = loginType;
  }

  public LoginBody cid(Integer cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Get cid
   * @return cid
  **/
  @Schema(example = "2", description = "")
  public Integer getCid() {
    return cid;
  }

  public void setCid(Integer cid) {
    this.cid = cid;
  }

  public LoginBody sid(Integer sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @Schema(example = "66", description = "")
  public Integer getSid() {
    return sid;
  }

  public void setSid(Integer sid) {
    this.sid = sid;
  }

  public LoginBody pid(Integer pid) {
    this.pid = pid;
    return this;
  }

   /**
   * Get pid
   * @return pid
  **/
  @Schema(example = "-1", description = "")
  public Integer getPid() {
    return pid;
  }

  public void setPid(Integer pid) {
    this.pid = pid;
  }

  public LoginBody cn(Integer cn) {
    this.cn = cn;
    return this;
  }

   /**
   * Get cn
   * @return cn
  **/
  @Schema(example = "3", description = "")
  public Integer getCn() {
    return cn;
  }

  public void setCn(Integer cn) {
    this.cn = cn;
  }

  public LoginBody sft(Integer sft) {
    this.sft = sft;
    return this;
  }

   /**
   * Get sft
   * @return sft
  **/
  @Schema(example = "2", description = "")
  public Integer getSft() {
    return sft;
  }

  public void setSft(Integer sft) {
    this.sft = sft;
  }

  public LoginBody scid(Integer scid) {
    this.scid = scid;
    return this;
  }

   /**
   * Get scid
   * @return scid
  **/
  @Schema(example = "22", description = "")
  public Integer getScid() {
    return scid;
  }

  public void setScid(Integer scid) {
    this.scid = scid;
  }

  public LoginBody UN(String UN) {
    this.UN = UN;
    return this;
  }

   /**
   * Get UN
   * @return UN
  **/
  @Schema(example = "ИвановИИ", description = "")
  public String getUN() {
    return UN;
  }

  public void setUN(String UN) {
    this.UN = UN;
  }

  public LoginBody PW(String PW) {
    this.PW = PW;
    return this;
  }

   /**
   * Get PW
   * @return PW
  **/
  @Schema(example = "913c33", description = "")
  public String getPW() {
    return PW;
  }

  public void setPW(String PW) {
    this.PW = PW;
  }

  public LoginBody lt(Integer lt) {
    this.lt = lt;
    return this;
  }

   /**
   * Get lt
   * @return lt
  **/
  @Schema(example = "728627461", description = "")
  public Integer getLt() {
    return lt;
  }

  public void setLt(Integer lt) {
    this.lt = lt;
  }

  public LoginBody pw2(String pw2) {
    this.pw2 = pw2;
    return this;
  }

   /**
   * Get pw2
   * @return pw2
  **/
  @Schema(example = "913c329378a9055fed2d7cb971012ab9", description = "")
  public String getPw2() {
    return pw2;
  }

  public void setPw2(String pw2) {
    this.pw2 = pw2;
  }

  public LoginBody ver(Integer ver) {
    this.ver = ver;
    return this;
  }

   /**
   * Get ver
   * @return ver
  **/
  @Schema(example = "768250818", description = "")
  public Integer getVer() {
    return ver;
  }

  public void setVer(Integer ver) {
    this.ver = ver;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginBody loginBody = (LoginBody) o;
    return Objects.equals(this.loginType, loginBody.loginType) &&
        Objects.equals(this.cid, loginBody.cid) &&
        Objects.equals(this.sid, loginBody.sid) &&
        Objects.equals(this.pid, loginBody.pid) &&
        Objects.equals(this.cn, loginBody.cn) &&
        Objects.equals(this.sft, loginBody.sft) &&
        Objects.equals(this.scid, loginBody.scid) &&
        Objects.equals(this.UN, loginBody.UN) &&
        Objects.equals(this.PW, loginBody.PW) &&
        Objects.equals(this.lt, loginBody.lt) &&
        Objects.equals(this.pw2, loginBody.pw2) &&
        Objects.equals(this.ver, loginBody.ver);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loginType, cid, sid, pid, cn, sft, scid, UN, PW, lt, pw2, ver);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginBody {\n");
    
    sb.append("    loginType: ").append(toIndentedString(loginType)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    cn: ").append(toIndentedString(cn)).append("\n");
    sb.append("    sft: ").append(toIndentedString(sft)).append("\n");
    sb.append("    scid: ").append(toIndentedString(scid)).append("\n");
    sb.append("    UN: ").append(toIndentedString(UN)).append("\n");
    sb.append("    PW: ").append(toIndentedString(PW)).append("\n");
    sb.append("    lt: ").append(toIndentedString(lt)).append("\n");
    sb.append("    pw2: ").append(toIndentedString(pw2)).append("\n");
    sb.append("    ver: ").append(toIndentedString(ver)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
