/*
 * NetSchool
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * StudentDiaryInitStudents
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-10-24T12:37:15.210Z[GMT]")
public class StudentDiaryInitStudents {
  @SerializedName("studentId")
  private Integer studentId = null;

  @SerializedName("nickName")
  private String nickName = null;

  @SerializedName("className")
  private Object className = null;

  @SerializedName("classId")
  private Integer classId = null;

  @SerializedName("iupGrade")
  private Integer iupGrade = null;

  public StudentDiaryInitStudents studentId(Integer studentId) {
    this.studentId = studentId;
    return this;
  }

   /**
   * Get studentId
   * @return studentId
  **/
  @Schema(example = "1111", description = "")
  public Integer getStudentId() {
    return studentId;
  }

  public void setStudentId(Integer studentId) {
    this.studentId = studentId;
  }

  public StudentDiaryInitStudents nickName(String nickName) {
    this.nickName = nickName;
    return this;
  }

   /**
   * Get nickName
   * @return nickName
  **/
  @Schema(example = "Иванов Иван", description = "")
  public String getNickName() {
    return nickName;
  }

  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  public StudentDiaryInitStudents className(Object className) {
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @Schema(example = "nil", description = "")
  public Object getClassName() {
    return className;
  }

  public void setClassName(Object className) {
    this.className = className;
  }

  public StudentDiaryInitStudents classId(Integer classId) {
    this.classId = classId;
    return this;
  }

   /**
   * Get classId
   * @return classId
  **/
  @Schema(example = "0", description = "")
  public Integer getClassId() {
    return classId;
  }

  public void setClassId(Integer classId) {
    this.classId = classId;
  }

  public StudentDiaryInitStudents iupGrade(Integer iupGrade) {
    this.iupGrade = iupGrade;
    return this;
  }

   /**
   * Get iupGrade
   * @return iupGrade
  **/
  @Schema(example = "0", description = "")
  public Integer getIupGrade() {
    return iupGrade;
  }

  public void setIupGrade(Integer iupGrade) {
    this.iupGrade = iupGrade;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentDiaryInitStudents studentDiaryInitStudents = (StudentDiaryInitStudents) o;
    return Objects.equals(this.studentId, studentDiaryInitStudents.studentId) &&
        Objects.equals(this.nickName, studentDiaryInitStudents.nickName) &&
        Objects.equals(this.className, studentDiaryInitStudents.className) &&
        Objects.equals(this.classId, studentDiaryInitStudents.classId) &&
        Objects.equals(this.iupGrade, studentDiaryInitStudents.iupGrade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studentId, nickName, className, classId, iupGrade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentDiaryInitStudents {\n");
    
    sb.append("    studentId: ").append(toIndentedString(studentId)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    iupGrade: ").append(toIndentedString(iupGrade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
