/* 
 * NetSchool
 *
 * The API for the NetSchool irTech project
 *
 * OpenAPI spec version: 5.10.63221
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MysettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MysettingsApiTests
    {
        private MysettingsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MysettingsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MysettingsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MysettingsApi
            //Assert.IsInstanceOfType(typeof(MysettingsApi), instance, "instance is a MysettingsApi");
        }

        /// <summary>
        /// Test Mysettings
        /// </summary>
        [Test]
        public void MysettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string at = null;
            //var response = instance.Mysettings(at);
            //Assert.IsInstanceOf<MySettings> (response, "response is MySettings");
        }
        /// <summary>
        /// Test Yearlist
        /// </summary>
        [Test]
        public void YearlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string at = null;
            //var response = instance.Yearlist(at);
            //Assert.IsInstanceOf<MySettingsYears> (response, "response is MySettingsYears");
        }
    }

}
