# coding: utf-8

"""
    NetSchool

    The API for the NetSchool irTech project  # noqa: E501

    OpenAPI spec version: 4.30.43656
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiaryAssignDetailsAttachments(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'original_file_name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'original_file_name': 'originalFileName',
        'description': 'description'
    }

    def __init__(self, id=None, name=None, original_file_name=None, description=None):  # noqa: E501
        """DiaryAssignDetailsAttachments - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._original_file_name = None
        self._description = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if original_file_name is not None:
            self.original_file_name = original_file_name
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this DiaryAssignDetailsAttachments.  # noqa: E501


        :return: The id of this DiaryAssignDetailsAttachments.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DiaryAssignDetailsAttachments.


        :param id: The id of this DiaryAssignDetailsAttachments.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this DiaryAssignDetailsAttachments.  # noqa: E501


        :return: The name of this DiaryAssignDetailsAttachments.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DiaryAssignDetailsAttachments.


        :param name: The name of this DiaryAssignDetailsAttachments.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def original_file_name(self):
        """Gets the original_file_name of this DiaryAssignDetailsAttachments.  # noqa: E501


        :return: The original_file_name of this DiaryAssignDetailsAttachments.  # noqa: E501
        :rtype: str
        """
        return self._original_file_name

    @original_file_name.setter
    def original_file_name(self, original_file_name):
        """Sets the original_file_name of this DiaryAssignDetailsAttachments.


        :param original_file_name: The original_file_name of this DiaryAssignDetailsAttachments.  # noqa: E501
        :type: str
        """

        self._original_file_name = original_file_name

    @property
    def description(self):
        """Gets the description of this DiaryAssignDetailsAttachments.  # noqa: E501


        :return: The description of this DiaryAssignDetailsAttachments.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DiaryAssignDetailsAttachments.


        :param description: The description of this DiaryAssignDetailsAttachments.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiaryAssignDetailsAttachments, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiaryAssignDetailsAttachments):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
