# coding: utf-8

"""
    NetSchool

    The API for the NetSchool irTech project  # noqa: E501

    OpenAPI spec version: 5.10.63221
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetAuthData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lt': 'str',
        'ver': 'str',
        'salt': 'str'
    }

    attribute_map = {
        'lt': 'lt',
        'ver': 'ver',
        'salt': 'salt'
    }

    def __init__(self, lt=None, ver=None, salt=None):  # noqa: E501
        """GetAuthData - a model defined in Swagger"""  # noqa: E501
        self._lt = None
        self._ver = None
        self._salt = None
        self.discriminator = None
        if lt is not None:
            self.lt = lt
        if ver is not None:
            self.ver = ver
        if salt is not None:
            self.salt = salt

    @property
    def lt(self):
        """Gets the lt of this GetAuthData.  # noqa: E501


        :return: The lt of this GetAuthData.  # noqa: E501
        :rtype: str
        """
        return self._lt

    @lt.setter
    def lt(self, lt):
        """Sets the lt of this GetAuthData.


        :param lt: The lt of this GetAuthData.  # noqa: E501
        :type: str
        """

        self._lt = lt

    @property
    def ver(self):
        """Gets the ver of this GetAuthData.  # noqa: E501


        :return: The ver of this GetAuthData.  # noqa: E501
        :rtype: str
        """
        return self._ver

    @ver.setter
    def ver(self, ver):
        """Sets the ver of this GetAuthData.


        :param ver: The ver of this GetAuthData.  # noqa: E501
        :type: str
        """

        self._ver = ver

    @property
    def salt(self):
        """Gets the salt of this GetAuthData.  # noqa: E501


        :return: The salt of this GetAuthData.  # noqa: E501
        :rtype: str
        """
        return self._salt

    @salt.setter
    def salt(self, salt):
        """Sets the salt of this GetAuthData.


        :param salt: The salt of this GetAuthData.  # noqa: E501
        :type: str
        """

        self._salt = salt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetAuthData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetAuthData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
